# Generated by Django 5.1.4 on 2024-12-25 19:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('encrypted_file', models.BinaryField()),
                ('key', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.EmailField(max_length=254)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2025, 1, 1, 19, 43, 52, 430192, tzinfo=datetime.timezone.utc))),
                ('permission', models.CharField(choices=[('read', 'Read'), ('edit', 'Edit')], max_length=50)),
                ('secure_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.securefile')),
            ],
        ),
    ]
